### ISSUE TITLE
[Feature] Button

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-css#1]
# [Demo](https://discord-open-source.github.io/discord-css/test/button.html)

- [x] Text
- [x] Icon
- [x] Disabled
- [x] Outline

added in ca50f88

![Buttons](https://user-images.githubusercontent.com/34555296/103567474-31250b80-4ec4-11eb-99b8-b639871878df.png)

**Comment by xNaCly** [comment]
Radio?

**Comment by Flam3rboy** [comment]
> Radio?

seperate issue

**Comment by xNaCly** [comment]
its a button

**Comment by Flam3rboy** [comment]
make a seperate button in another issue extra for radio
