### ISSUE TITLE
[Feature] Slider

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-css#10]
- [x] slider
![image](https://user-images.githubusercontent.com/34555296/103599274-0e671700-4f05-11eb-8ce8-47bbf4025b98.png)

- [ ] value tooltip
![image](https://user-images.githubusercontent.com/34555296/103599292-17f07f00-4f05-11eb-9ba7-0eb5c2d3ad76.png)

**Comment by BuilderHD** [comment]
I'm working on it
