### ISSUE TITLE
[Feature] Switch

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-css#2]
- [x] simple switch:
  _inactive_
 ![image](https://user-images.githubusercontent.com/34555296/103575215-ab0fc180-4ed1-11eb-9add-c5cc41ccc795.png)
  _active_
 ![image](https://user-images.githubusercontent.com/47723417/114087046-adf4c680-98b3-11eb-8c1c-40f48cae208c.png)
- [x] three states:
![image](https://user-images.githubusercontent.com/34555296/103575236-b4009300-4ed1-11eb-88d8-5bf2553be224.png)

**Comment by Flam3rboy** [comment]
finished: https://fosscord.github.io/fosscord-css/test/switch.html

**Comment by ThatOneCalculator** [comment]
> finished: https://fosscord.github.io/fosscord-css/test/switch.html

These look really nice, but the regular switches are missing the check and x in the on/off states. Is it planned to integrate them or no?

**Comment by Flam3rboy** [comment]
or I forgot them xD

**Comment by ThatOneCalculator** [comment]
Cool. Can we expect that in the near future?

**Comment by Flam3rboy** [comment]
> Cool. Can we expect that in the near future?

done
