### ISSUE TITLE
[Feature] Dropdown

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-css#4]
- [x] Basic Dropdown with values e.g:
![image](https://user-images.githubusercontent.com/34555296/103575985-c0392000-4ed2-11eb-88a1-2ec2dd873a63.png)
- [x] Text Channel icons e.g:
![image](https://user-images.githubusercontent.com/34555296/103576161-00000780-4ed3-11eb-881a-2cf78a036a2d.png)

^ both channels with optional category

**Comment by ThatOneCalculator** [comment]
Any progress update on this?

**Comment by Flam3rboy** [comment]
I think we should close/archive this repository as we do the components on the react native client repository with React Native Stylesheets instead of css

**Comment by ThatOneCalculator** [comment]
> I think we should close/archive this repository as we do the components on the react native client repository with React Native Stylesheets instead of css

Ah, that's a shame. I'm planning on using Fosscord's CSS in one of my own projects (with credit of course), it would've been cool to have a dropdown menu like this. Best of luck on Fosscord!

**Comment by Flam3rboy** [comment]
yeah especially for bot dashboards. We could work on it, if we are finished with the other parts.

**Comment by Flam3rboy** [comment]
on it

**Comment by Flam3rboy** [comment]
done: https://fosscord.github.io/fosscord-css/test/dropdown.html
![image](https://user-images.githubusercontent.com/34555296/114310223-63a95a80-9aea-11eb-9084-18b763284717.png)

**Comment by KibaShop** [comment]
lol
